# Generated by Django 5.0.4 on 2024-05-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место выполнения')),
                ('time', models.DateTimeField(verbose_name='время выполнения')),
                ('action', models.CharField(max_length=200, verbose_name='действие')),
                ('is_nice_habit', models.BooleanField(blank=True, null=True, verbose_name='приятность привычки')),
                ('related_habit', models.CharField(blank=True, max_length=200, null=True, verbose_name='связанная привычка')),
                ('periodicity', models.CharField(max_length=50, verbose_name='интервал между привычками в днях')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='вознаграждение')),
                ('time_to_complete', models.PositiveSmallIntegerField(verbose_name='время на выполнение в секундах')),
                ('is_public', models.BooleanField(verbose_name='публичность')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
